//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ED6BaseHook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ED6BaseHook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0010000001
        ///0010000002
        ///0010000003
        ///0010000004
        ///0010000005
        ///0010000007
        ///0010000010
        ///0010000011
        ///0010000012
        ///0010000015
        ///0010000016
        ///0010000019
        ///0010000020
        ///0010000021
        ///0010000022
        ///0010000026
        ///0010000027
        ///0010000030
        ///0010000031
        ///0010000033
        ///0010000034
        ///0010000038
        ///0010000039
        ///0010000040
        ///0010000041
        ///0010000044
        ///0010000045
        ///0010000047
        ///0010000048
        ///0010000049
        ///0010000050
        ///0010000053
        ///0010000057
        ///0010000060
        ///0010000063
        ///0010000070
        ///0010000077
        ///0010000078
        ///0010000079
        ///0010000082
        ///0010000083
        ///0010000089
        ///00100000 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VoiceIDs {
            get {
                return ResourceManager.GetString("VoiceIDs", resourceCulture);
            }
        }
    }
}
